# If the page was not updated by the username specified here, throw an error.
# If this setting is ommited - auth.username is used for checks.
author = ""

[pages]
[pages.default]
# Space should be defined as abbreviation, otherwise 403 error would be generated
page_space = "default space"
[pages.page1]
page_title = "Some page name"
# The name of text file with page contents
page_file = "some_file.confluencewiki"
# If specified - overrides the default page_space
page_space = "some_space"

[pages.page2]
page_title = "Some other page name"
page_file = "some_other_file.confluencewiki"

[auth]
# URL of confluence instance
confluence_url = ""
# Username for authentication
username = ""
# Password may also be supplied through --password option or from an environment variable CONFLUENCE_PASSWORD
password = ""
# Whether the confluence instance is a "cloud" one
is_cloud = false

